service: demo-s3-triggered-lambda-service
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
plugins:
  - ../../dist
functions:
  test:
    handler: handler.test'
    events:
      - s3:
          bucket:
            Ref: MyBucket
          existing: true
